# Generated by Django 4.0.3 on 2022-04-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_owner_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='quantity',
            new_name='medicine_quantity',
        ),
    ]
