# Generated by Django 4.0.3 on 2022-04-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_quantity_medicine_medicine_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
