# Generated by Django 4.0.3 on 2022-04-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_quantity', models.CharField(max_length=100)),
                ('medicine_price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
