# Generated by Django 4.0.3 on 2022-04-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(default='', upload_to='medicine/'),
        ),
    ]
