# Generated by Django 4.0.3 on 2022-04-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_quantity', models.CharField(max_length=100)),
                ('medicine_price', models.CharField(max_length=100)),
                ('medicine_image', models.ImageField(upload_to='medicine/')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
