# Generated by Django 4.0.3 on 2022-04-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
