# Generated by Django 4.0.3 on 2022-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='purchace_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_cost',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
